{% set name = "sp-installer-menu" %}
{% set version = "0.1.0" %}
{% set build = 1 %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: {{ build }}
  # skip: true  # [not linux]
  noarch: python
  script:
    - pushd {{ RECIPE_DIR }}
    - python make_menu.py

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f ${CONDA_PREFIX}/Menu/sp-installer-menu.json
    - test -f ${CONDA_PREFIX}/Menu/spi_sys_info.py
    - test -f ${CONDA_PREFIX}/Menu/sp-installer-menu_open_prompt.applescript
    - test -f ${CONDA_PREFIX}/Menu/sp-installer-menu_open_prompt.sh
    - test -f ${CONDA_PREFIX}/Menu/sp-installer-menu_open_prompt.bat
    # Check we didn't forget any icons
    - test `ls ${CONDA_PREFIX}/Menu/sp-installer-menu_console.* | wc -l` -eq 3
    - test `ls ${CONDA_PREFIX}/Menu/sp-installer-menu_info.*    | wc -l` -eq 3
    - test `ls ${CONDA_PREFIX}/Menu/sp-installer-menu_web.*     | wc -l` -eq 3
    - test `ls ${CONDA_PREFIX}/Menu/sp-installer-menu_forum.*   | wc -l` -eq 3
    - test -f ${CONDA_PREFIX}/Menu/spi_mac_folder_icon.png

about:
  home: http://learn.scientific-python.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Menu items for the Scientific Python installer
  description: |
    This package provides various icons, configuration files and scripts for
    use with the Scientific Python data science packages installer.
  doc_url: http://learn.scientific-python.org
  dev_url: https://github.com/scientific-python/installer
extra:
  recipe-maintainers:
    - matthew-brett
    - drammock
